# docker-compose.yml

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3-management
#    restart: always
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#  redis:
#    container_name: cache
#    image: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#  elasticsearch:
#    container_name: elasticsearch
#    image: elasticsearch:8.11.1
#    restart: always
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - es-data:/usr/share/elasticsearch/data
volumes:
  mysql-data:
  rabbitmq-data:
  redis-data:
  es-data: