spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bi
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
openai:
  token: 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
  proxy:
    host: '127.0.0.1'
    port: 7890
cos:
  secretId: AKIDHmZgC3trw5EdOIF501bb8GZ4oT4lP3lX
  secretKey: 217CMWODyljhYJ60oaTrCYE2mjAlXIAH
  region: ap-hongkong
  bucket: smatbi-1253865806