spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bi
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 5000
  session:
    timeout: 2592000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
openai:
  token: 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
  proxy:
    host: '127.0.0.1'
    port: 7890
cos:
  secretId: AKIDHmZgC3trw5EdOIF501bb8GZ4oT4lP3lX
  secretKey: 217CMWODyljhYJ60oaTrCYE2mjAlXIAH
  region: ap-hongkong
  bucket: smatbi-1253865806
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.robert.smartbi.demo.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN