spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/bi
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: guest
    username: guest
  data:
    redis:
      host: redis
      port: 6379
      database: 1
